// Catalogs every editable section + field across the 3 main pages.
// The dashboard reads this to render its editor.

export type SectionField =
  | { kind: "text"; id: string; label: string; default: string; multiline?: boolean }
  | { kind: "image"; id: string; label: string; default: string }
  | { kind: "variant"; id: string; label: string; options: { value: string; label: string }[]; default: string };

export type Section = {
  id: string;
  label: string;
  page: "home" | "merchant" | "user";
  anchor: string; // URL hash to scroll to (best-effort)
  fields: SectionField[];
};

export const SECTIONS: Section[] = [
  // ─────────────────── HOME ───────────────────
  {
    id: "home.hero",
    page: "home",
    label: "Hero",
    anchor: "/#hero",
    fields: [
      { kind: "text", id: "home.hero.eyebrow", label: "Eyebrow", default: "Open Liquidity Network" },
      { kind: "text", id: "home.hero.title.line1", label: "Headline · line 1", default: "Settle money globally through " },
      { kind: "text", id: "home.hero.title.line2", label: "Headline · italic", default: "open markets." },
      { kind: "text", id: "home.hero.sub", label: "Subtitle", default: "Blip connects users with verified merchants who compete to settle payments faster, safer, and at better rates.", multiline: true },
    ],
  },
  {
    id: "home.merchant-section",
    page: "home",
    label: "Powered by Merchants",
    anchor: "/#merchants",
    fields: [
      { kind: "text", id: "home.merchant.eyebrow", label: "Eyebrow", default: "Powered by Merchants" },
      { kind: "text", id: "home.merchant.title.pre", label: "Title · pre", default: "Merchants provide liquidity. " },
      { kind: "text", id: "home.merchant.title.accent", label: "Title · accent", default: "Earn on every order." },
      { kind: "text", id: "home.merchant.sub", label: "Subtitle", default: "Verified merchants bid live, set their own spread, and capture profit on every settlement — paid out instantly, on-chain.", multiline: true },
      {
        kind: "variant",
        id: "blip:merchant-cards-variant",
        label: "Cards variant",
        options: [
          { value: "mixed", label: "Mixed · animated + scene" },
          { value: "apple", label: "Apple-style · product cards" },
          { value: "clear", label: "Smart app · clear hero" },
          { value: "kinetic", label: "Dashboard · dark kinetic" },
          { value: "live-rows", label: "Dashboard · live rows" },
          { value: "editorial", label: "Editorial · live-data" },
          { value: "painted", label: "Painted · Gemini scenes" },
          { value: "card-hero", label: "Card hero · 3 painted" },
          { value: "app-style", label: "Merchant · app-style" },
          { value: "local-rows", label: "Local · dashboard merchant" },
        ],
        default: "mixed",
      },
    ],
  },

  {
    id: "home.bankless",
    page: "home",
    label: "Bankless / Global liquidity",
    anchor: "/#bankless",
    fields: [
      { kind: "text", id: "home.bankless.eyebrow", label: "Eyebrow", default: "Global liquidity network" },
      { kind: "text", id: "home.bankless.title.line1", label: "Title · line 1", default: "Banking," },
      { kind: "text", id: "home.bankless.title.line2", label: "Title · line 2", default: "without the bank." },
      { kind: "text", id: "home.bankless.sub", label: "Subtitle", default: "A global liquidity marketplace where transactions are fulfilled by participants instead of traditional banking rails.", multiline: true },
      { kind: "text", id: "home.bankless.outro.line1", label: "Outro · line 1", default: "Settlement becomes a marketplace" },
      { kind: "text", id: "home.bankless.outro.line2", label: "Outro · line 2", default: "instead of a monopoly." },
    ],
  },
  {
    id: "home.howitworks",
    page: "home",
    label: "How it works (mobile intro)",
    anchor: "/#howitworks",
    fields: [
      { kind: "text", id: "home.howitworks.eyebrow", label: "Eyebrow", default: "How it works" },
      { kind: "text", id: "home.howitworks.title.line1", label: "Title · line 1", default: "From wallet" },
      { kind: "text", id: "home.howitworks.title.line2", label: "Title · line 2", default: "to cash." },
      { kind: "text", id: "home.howitworks.sub", label: "Subtitle", default: "Six stages. Under sixty seconds.", multiline: true },
    ],
  },
  {
    id: "home.protocol",
    page: "home",
    label: "Blip Protocol interstitial",
    anchor: "/#protocol",
    fields: [
      { kind: "text", id: "home.protocol.eyebrow", label: "Eyebrow", default: "Introducing" },
      { kind: "text", id: "home.protocol.title.pre", label: "Title · pre", default: "The " },
      { kind: "text", id: "home.protocol.title.accent", label: "Title · accent", default: "Blip Protocol" },
    ],
  },
  {
    id: "home.markets",
    page: "home",
    label: "Blip Markets (live marketplace)",
    anchor: "/#blip-markets-section",
    fields: [
      { kind: "text", id: "home.markets.eyebrow", label: "Eyebrow", default: "Blip Markets" },
      { kind: "text", id: "home.markets.title.line1", label: "Title · line 1", default: "A live marketplace" },
      { kind: "text", id: "home.markets.title.line2", label: "Title · line 2", default: "for global settlement." },
      { kind: "text", id: "home.markets.sub", label: "Subtitle", default: "Watch real money move. Merchants compete. Trades clear in seconds.", multiline: true },
      { kind: "text", id: "home.markets.cta.primary", label: "CTA · primary", default: "Join Waitlist" },
      { kind: "text", id: "home.markets.cta.secondary", label: "CTA · secondary", default: "Explore Blip Market" },
    ],
  },
  {
    id: "home.usecases",
    page: "home",
    label: "Use cases (Built for everyone)",
    anchor: "/#usecases",
    fields: [
      { kind: "text", id: "home.usecases.title", label: "Main title", default: "Built for everyone." },
      { kind: "text", id: "home.usecases.users.eyebrow", label: "Users · eyebrow", default: "For users" },
      { kind: "text", id: "home.usecases.users.title.line1", label: "Users · title line 1", default: "Send USDT." },
      { kind: "text", id: "home.usecases.users.title.line2", label: "Users · title line 2", default: "Get cash delivered." },
      { kind: "text", id: "home.usecases.users.desc", label: "Users · description", default: "Cross-border remittance in under 60 seconds. No banks. No forms. Recipient gets local currency instantly.", multiline: true },
      { kind: "text", id: "home.usecases.merchants.eyebrow", label: "Merchants · eyebrow", default: "For merchants" },
      { kind: "text", id: "home.usecases.merchants.title.line1", label: "Merchants · title line 1", default: "Accept crypto." },
      { kind: "text", id: "home.usecases.merchants.title.line2", label: "Merchants · title line 2", default: "Earn on every trade." },
      { kind: "text", id: "home.usecases.merchants.desc", label: "Merchants · description", default: "Instant settlement. Zero chargebacks. Margin on every order.", multiline: true },
      { kind: "text", id: "home.usecases.lps.eyebrow", label: "LPs · eyebrow", default: "For liquidity providers" },
      { kind: "text", id: "home.usecases.lps.title.line1", label: "LPs · title line 1", default: "Deploy capital." },
      { kind: "text", id: "home.usecases.lps.title.line2", label: "LPs · title line 2", default: "Capture spread." },
      { kind: "text", id: "home.usecases.lps.desc", label: "LPs · description", default: "Fund settlement routes. Earn infrastructure yield. Full control.", multiline: true },
    ],
  },
  {
    id: "home.liquidity",
    page: "home",
    label: "Liquidity layer (comparison)",
    anchor: "/#liquidity",
    fields: [
      { kind: "text", id: "home.liquidity.eyebrow", label: "Eyebrow", default: "Why Blip" },
      { kind: "text", id: "home.liquidity.title", label: "Title", default: "Traditional rails vs Blip Protocol." },
      { kind: "text", id: "home.liquidity.cta", label: "CTA", default: "Get early access" },
    ],
  },
  {
    id: "home.network",
    page: "home",
    label: "Live network feed",
    anchor: "/#network",
    fields: [
      { kind: "text", id: "home.network.eyebrow", label: "Eyebrow", default: "Live network" },
      { kind: "text", id: "home.network.title", label: "Title", default: "The network is live." },
      { kind: "text", id: "home.network.sub", label: "Subtitle", default: "Real settlements. Real earnings. Real points. Early participants are being rewarded.", multiline: true },
      { kind: "text", id: "home.network.cta", label: "CTA", default: "Start earning points" },
      { kind: "text", id: "home.network.cta.note", label: "CTA note", default: "Early participants are being rewarded. Join early access.", multiline: true },
    ],
  },
  {
    id: "home.appshowcase",
    page: "home",
    label: "App showcase (Built to be felt)",
    anchor: "/#appshowcase",
    fields: [
      { kind: "text", id: "home.appshowcase.eyebrow", label: "Eyebrow", default: "The App" },
      { kind: "text", id: "home.appshowcase.title", label: "Title", default: "Built to be felt." },
    ],
  },
  {
    id: "home.trust",
    page: "home",
    label: "Trust (Built to not break)",
    anchor: "/#trust",
    fields: [
      { kind: "text", id: "home.trust.title", label: "Title", default: "Built to not break." },
    ],
  },
  {
    id: "home.cta",
    page: "home",
    label: "Final CTA (next chapter)",
    anchor: "/#cta",
    fields: [
      { kind: "text", id: "home.cta.eyebrow", label: "Eyebrow", default: "The next chapter" },
      { kind: "text", id: "home.cta.title.pre", label: "Title · pre", default: "The new financial rail is " },
      { kind: "text", id: "home.cta.title.accent", label: "Title · accent", default: "being built." },
      { kind: "text", id: "home.cta.button.primary", label: "CTA · primary", default: "Join waitlist" },
      { kind: "text", id: "home.cta.button.secondary", label: "CTA · secondary", default: "Provide liquidity" },
    ],
  },

  // ─────────────────── MERCHANT ───────────────────
  {
    id: "merchant.hero",
    page: "merchant",
    label: "Merchant hero",
    anchor: "/merchant",
    fields: [
      { kind: "text", id: "merchant.hero.eyebrow", label: "Eyebrow", default: "Merchant-First Protocol" },
      { kind: "text", id: "merchant.hero.title.pre", label: "Title · pre", default: "You set the margin. " },
      { kind: "text", id: "merchant.hero.title.accent", label: "Title · accent", default: "You win the order." },
      { kind: "text", id: "merchant.hero.sub", label: "Subtitle", default: "Orders route to you through Blip Market — paid on-chain, no banks, no chargebacks. Earn on every settlement.", multiline: true },
      { kind: "text", id: "merchant.hero.cta.primary", label: "CTA · primary", default: "Apply as Merchant" },
      { kind: "text", id: "merchant.hero.cta.secondary", label: "CTA · secondary", default: "Merchant Sign-in" },
    ],
  },
  {
    id: "merchant.why",
    page: "merchant",
    label: "Why merchants choose Blip",
    anchor: "/merchant#why",
    fields: [
      { kind: "text", id: "merchant.why.title.pre", label: "Title · pre", default: "Why Merchants " },
      { kind: "text", id: "merchant.why.title.accent", label: "Title · accent", default: "Choose" },
      { kind: "text", id: "merchant.why.title.post", label: "Title · post", default: " Blip?" },
      { kind: "text", id: "merchant.why.sub", label: "Subtitle", default: "Built for speed, control and repeat volume.", multiline: true },
    ],
  },
  {
    id: "merchant.dashboard",
    page: "merchant",
    label: "Merchant dashboard (command center)",
    anchor: "/merchant#dashboard",
    fields: [
      { kind: "text", id: "merchant.dashboard.eyebrow", label: "Eyebrow", default: "Merchant Dashboard" },
      { kind: "text", id: "merchant.dashboard.title.pre", label: "Title · pre", default: "Your " },
      { kind: "text", id: "merchant.dashboard.title.accent", label: "Title · accent", default: "command" },
      { kind: "text", id: "merchant.dashboard.title.post", label: "Title · post", default: " center" },
      { kind: "text", id: "merchant.dashboard.sub", label: "Subtitle", default: "Everything needed to run a desk, without the clutter.", multiline: true },
    ],
  },
  {
    id: "merchant.pricing",
    page: "merchant",
    label: "Pricing controls",
    anchor: "/merchant#pricing",
    fields: [
      { kind: "text", id: "merchant.pricing.eyebrow", label: "Eyebrow", default: "Pricing" },
      { kind: "text", id: "merchant.pricing.title.pre", label: "Title · pre", default: "You " },
      { kind: "text", id: "merchant.pricing.title.accent", label: "Title · accent", default: "control pricing." },
      { kind: "text", id: "merchant.pricing.title.post", label: "Title · post", default: "We make it simple." },
      { kind: "text", id: "merchant.pricing.sub", label: "Subtitle", default: "Blip shows a live market reference rate. Adjust your quote within allowed ranges to win orders faster.", multiline: true },
    ],
  },
  {
    id: "merchant.rollout",
    page: "merchant",
    label: "Invite-only rollout",
    anchor: "/merchant#rollout",
    fields: [
      { kind: "text", id: "merchant.rollout.eyebrow", label: "Eyebrow", default: "Rollout" },
      { kind: "text", id: "merchant.rollout.title.pre", label: "Title · pre", default: "Invite-only " },
      { kind: "text", id: "merchant.rollout.title.accent", label: "Title · accent", default: "rollout." },
      { kind: "text", id: "merchant.rollout.sub", label: "Subtitle", default: "We're expanding in stages. Get in early and shape the protocol.", multiline: true },
    ],
  },
  {
    id: "merchant.requirements",
    page: "merchant",
    label: "Requirements (who should apply)",
    anchor: "/merchant#requirements",
    fields: [
      { kind: "text", id: "merchant.requirements.eyebrow", label: "Eyebrow", default: "Requirements" },
      { kind: "text", id: "merchant.requirements.title.pre", label: "Title · pre", default: "Who should " },
      { kind: "text", id: "merchant.requirements.title.accent", label: "Title · accent", default: "apply." },
      { kind: "text", id: "merchant.requirements.sub", label: "Subtitle", default: "Four simple boxes to tick. If you match, we want to talk to you.", multiline: true },
    ],
  },

  // ─────────────────── USER ───────────────────
  {
    id: "user.hero",
    page: "user",
    label: "User hero",
    anchor: "/user",
    fields: [
      { kind: "text", id: "user.hero.title.line1", label: "Headline · line 1", default: "Send crypto." },
      { kind: "text", id: "user.hero.title.line2", label: "Headline · line 2", default: "Get fiat instantly." },
      { kind: "text", id: "user.hero.sub", label: "Subtitle", default: "Convert USDT, USDC, or SOL to AED, INR, and more — settled on-chain, landed in your bank.", multiline: true },
      { kind: "text", id: "user.hero.cta.primary", label: "CTA · primary", default: "Join Waitlist" },
      { kind: "text", id: "user.hero.cta.secondary", label: "CTA · secondary", default: "See how it works" },
    ],
  },
  {
    id: "user.bestrates",
    page: "user",
    label: "Best rates · live market",
    anchor: "/user#bestrates",
    fields: [
      { kind: "text", id: "user.bestrates.eyebrow", label: "Eyebrow", default: "Best rates · live market" },
      { kind: "text", id: "user.bestrates.title.pre", label: "Title · pre", default: "We provide the " },
      { kind: "text", id: "user.bestrates.title.accent", label: "Title · accent", default: "best rates" },
      { kind: "text", id: "user.bestrates.title.post", label: "Title · post", default: " in the market." },
      { kind: "text", id: "user.bestrates.sub", label: "Subtitle", default: "Find a cheaper rate anywhere — we'll beat it. Live merchant quotes compete on every order so you always settle at the sharpest price.", multiline: true },
      { kind: "text", id: "user.bestrates.cta.primary", label: "CTA · primary", default: "Find the best rate" },
      { kind: "text", id: "user.bestrates.cta.secondary", label: "CTA · secondary", default: "Join waitlist" },
    ],
  },
  {
    id: "user.why",
    page: "user",
    label: "Why Blip (crypto out, cash in)",
    anchor: "/user#why",
    fields: [
      { kind: "text", id: "user.why.eyebrow", label: "Eyebrow", default: "Why Blip" },
      { kind: "text", id: "user.why.title.pre", label: "Title · pre", default: "Crypto out, " },
      { kind: "text", id: "user.why.title.accent", label: "Title · accent", default: "cash in." },
      { kind: "text", id: "user.why.title.post", label: "Title · post", default: "Under a minute." },
      { kind: "text", id: "user.why.sub", label: "Subtitle", default: "No banks. No delays. No middlemen. Blip matches you instantly with vetted merchants and settles via escrow.", multiline: true },
    ],
  },
  {
    id: "user.howitworks",
    page: "user",
    label: "How it works (four steps)",
    anchor: "/user#howitworks",
    fields: [
      { kind: "text", id: "user.howitworks.eyebrow", label: "Eyebrow", default: "How it works" },
      { kind: "text", id: "user.howitworks.title.pre", label: "Title · pre", default: "Four steps. " },
      { kind: "text", id: "user.howitworks.title.accent", label: "Title · accent", default: "Under a minute." },
    ],
  },
  {
    id: "user.safety",
    page: "user",
    label: "Safety (built for peace of mind)",
    anchor: "/user#safety",
    fields: [
      { kind: "text", id: "user.safety.eyebrow", label: "Eyebrow", default: "Safety" },
      { kind: "text", id: "user.safety.title.pre", label: "Title · pre", default: "Built for " },
      { kind: "text", id: "user.safety.title.accent", label: "Title · accent", default: "peace of mind." },
    ],
  },
  {
    id: "user.app-preview",
    page: "user",
    label: "App preview (One app, everything you need)",
    anchor: "/user#app-preview",
    fields: [
      { kind: "text", id: "user.app.eyebrow", label: "Eyebrow", default: "The app" },
      { kind: "text", id: "user.app.title.pre", label: "Title · pre", default: "One app. " },
      { kind: "text", id: "user.app.title.accent", label: "Title · accent", default: "Everything you need." },
      { kind: "text", id: "user.app.sub", label: "Subtitle", default: "Swap, settle, and track — all in a simple, fast interface.", multiline: true },
      { kind: "image", id: "user.app.screenshot", label: "Phone screenshot", default: "/app-home.png" },
    ],
  },
  {
    id: "user.cta",
    page: "user",
    label: "Ready to try Blip CTA",
    anchor: "/user#cta",
    fields: [
      { kind: "text", id: "user.cta.title.pre", label: "Title · pre", default: "Ready to try " },
      { kind: "text", id: "user.cta.title.accent", label: "Title · accent", default: "Blip?" },
      { kind: "text", id: "user.cta.sub", label: "Subtitle", default: "Join the waitlist. Early users get priority access and bonus rewards.", multiline: true },
    ],
  },

  // ─── USER ARRAYS (agent: user) ───
  {
    id: "user.why.features",
    page: "user",
    label: "Why Blip · feature cards",
    anchor: "/user#why",
    fields: [
      { kind: "text", id: "user.why.item0.title", label: "Feature 1 · title", default: "No middleman" },
      { kind: "text", id: "user.why.item0.desc", label: "Feature 1 · desc", default: "Swap peer-to-peer, settle on-chain." },
      { kind: "text", id: "user.why.item1.title", label: "Feature 2 · title", default: "Your wallet, your keys" },
      { kind: "text", id: "user.why.item1.desc", label: "Feature 2 · desc", default: "Non-custodial by design." },
      { kind: "text", id: "user.why.item2.title", label: "Feature 3 · title", default: "Fair market rates" },
      { kind: "text", id: "user.why.item2.desc", label: "Feature 3 · desc", default: "Live rates, transparent margin." },
      { kind: "text", id: "user.why.overlay.eyebrow", label: "Image overlay · eyebrow", default: "Instant" },
      { kind: "text", id: "user.why.overlay.line1", label: "Image overlay · line 1", default: "Crypto to cash." },
      { kind: "text", id: "user.why.overlay.line2", label: "Image overlay · line 2", default: "In under a minute." },
    ],
  },
  {
    id: "user.howitworks.steps",
    page: "user",
    label: "How it works · steps",
    anchor: "/user#howitworks",
    fields: [
      { kind: "text", id: "user.howitworks.step0.title", label: "Step 1 · title", default: "Connect wallet" },
      { kind: "text", id: "user.howitworks.step0.desc", label: "Step 1 · desc", default: "Phantom, Solflare, or any Solana-compatible wallet." },
      { kind: "text", id: "user.howitworks.step1.title", label: "Step 2 · title", default: "Pick your rate" },
      { kind: "text", id: "user.howitworks.step1.desc", label: "Step 2 · desc", default: "See live market rates. Pick the best merchant match." },
      { kind: "text", id: "user.howitworks.step2.title", label: "Step 3 · title", default: "Escrow locks funds" },
      { kind: "text", id: "user.howitworks.step2.desc", label: "Step 3 · desc", default: "Your crypto is locked on-chain. The merchant is committed." },
      { kind: "text", id: "user.howitworks.step3.title", label: "Step 4 · title", default: "Cash lands" },
      { kind: "text", id: "user.howitworks.step3.desc", label: "Step 4 · desc", default: "Fiat hits your bank. Escrow releases. Done." },
    ],
  },
  {
    id: "user.app-preview.tooltips",
    page: "user",
    label: "App preview · tooltips & stats",
    anchor: "/user#app-preview",
    fields: [
      { kind: "text", id: "user.app.line0.text", label: "Tooltip 1 · text", default: "Settle in under" },
      { kind: "text", id: "user.app.line0.accent", label: "Tooltip 1 · accent", default: "a minute." },
      { kind: "text", id: "user.app.line1.text", label: "Tooltip 2 · text", default: "Best rates," },
      { kind: "text", id: "user.app.line1.accent", label: "Tooltip 2 · accent", default: "guaranteed." },
      { kind: "text", id: "user.app.line2.text", label: "Tooltip 3 · text", default: "Your keys." },
      { kind: "text", id: "user.app.line2.accent", label: "Tooltip 3 · accent", default: "Your money." },
      { kind: "text", id: "user.app.line3.text", label: "Tooltip 4 · text", default: "Every order," },
      { kind: "text", id: "user.app.line3.accent", label: "Tooltip 4 · accent", default: "live." },
      { kind: "text", id: "user.app.stat0.val", label: "Stat 1 · value", default: "<60s" },
      { kind: "text", id: "user.app.stat0.lbl", label: "Stat 1 · label", default: "avg settlement" },
      { kind: "text", id: "user.app.stat1.val", label: "Stat 2 · value", default: "0%" },
      { kind: "text", id: "user.app.stat1.lbl", label: "Stat 2 · label", default: "protocol fees" },
      { kind: "text", id: "user.app.stat2.val", label: "Stat 3 · value", default: "24/7" },
      { kind: "text", id: "user.app.stat2.lbl", label: "Stat 3 · label", default: "always on" },
    ],
  },
  {
    id: "user.safety.cards",
    page: "user",
    label: "Safety · trust cards",
    anchor: "/user#safety",
    fields: [
      { kind: "text", id: "user.safety.card0.title", label: "Card 1 · title", default: "Non-custodial" },
      { kind: "text", id: "user.safety.card0.desc", label: "Card 1 · desc", default: "You hold your keys. We never touch your funds." },
      { kind: "text", id: "user.safety.card1.title", label: "Card 2 · title", default: "Escrow-backed" },
      { kind: "text", id: "user.safety.card1.desc", label: "Card 2 · desc", default: "Every trade protected by on-chain escrow." },
      { kind: "text", id: "user.safety.card2.title", label: "Card 3 · title", default: "Fully transparent" },
      { kind: "text", id: "user.safety.card2.desc", label: "Card 3 · desc", default: "Every transaction verifiable on Blip Scan." },
      { kind: "text", id: "user.safety.card3.title", label: "Card 4 · title", default: "Vetted merchants" },
      { kind: "text", id: "user.safety.card3.desc", label: "Card 4 · desc", default: "Reputation tracked. Non-performers removed." },
    ],
  },

  // ─── MERCHANT ARRAYS (agent: merchant) ───
  {
    id: "merchant.why.items",
    page: "merchant",
    label: "Why Blip · feature list",
    anchor: "/merchant#why",
    fields: [
      { kind: "text", id: "merchant.why.item1.title", label: "Item 1 · title", default: "No waiting" },
      { kind: "text", id: "merchant.why.item1.description", label: "Item 1 · description", default: "Requests come to you instead of you hunting buyers" },
      { kind: "text", id: "merchant.why.item2.title", label: "Item 2 · title", default: "More control" },
      { kind: "text", id: "merchant.why.item2.description", label: "Item 2 · description", default: "Filters, limits, and corridor selection" },
      { kind: "text", id: "merchant.why.item3.title", label: "Item 3 · title", default: "Faster execution" },
      { kind: "text", id: "merchant.why.item3.description", label: "Item 3 · description", default: "One flow, minimal steps, no noise" },
      { kind: "text", id: "merchant.why.item4.title", label: "Item 4 · title", default: "Lower risk" },
      { kind: "text", id: "merchant.why.item4.description", label: "Item 4 · description", default: "Escrow-first design reduces failed trades" },
      { kind: "text", id: "merchant.why.item5.title", label: "Item 5 · title", default: "Clear operations" },
      { kind: "text", id: "merchant.why.item5.description", label: "Item 5 · description", default: "Status timeline + trade history" },
      { kind: "text", id: "merchant.why.item6.title", label: "Item 6 · title", default: "Transparent proof" },
      { kind: "text", id: "merchant.why.item6.description", label: "Item 6 · description", default: "On-chain visibility via Blip Scan" },
    ],
  },
  {
    id: "merchant.dashboard.callouts",
    page: "merchant",
    label: "Dashboard · callouts",
    anchor: "/merchant#dashboard",
    fields: [
      { kind: "text", id: "merchant.dashboard.item1.title", label: "Callout 1 · title", default: "New Orders Feed" },
      { kind: "text", id: "merchant.dashboard.item1.description", label: "Callout 1 · description", default: "Real-time requests you can accept instantly" },
      { kind: "text", id: "merchant.dashboard.item2.title", label: "Callout 2 · title", default: "Margin Control" },
      { kind: "text", id: "merchant.dashboard.item2.description", label: "Callout 2 · description", default: "Adjust pricing within allowed ranges" },
      { kind: "text", id: "merchant.dashboard.item3.title", label: "Callout 3 · title", default: "Risk Controls" },
      { kind: "text", id: "merchant.dashboard.item3.description", label: "Callout 3 · description", default: "Amount limits, corridor filters, timeouts" },
      { kind: "text", id: "merchant.dashboard.item4.title", label: "Callout 4 · title", default: "Trade Timeline" },
      { kind: "text", id: "merchant.dashboard.item4.description", label: "Callout 4 · description", default: "Escrow → execution → release" },
      { kind: "text", id: "merchant.dashboard.item5.title", label: "Callout 5 · title", default: "Performance" },
      { kind: "text", id: "merchant.dashboard.item5.description", label: "Callout 5 · description", default: "Volume, speed, completion rate, profit view" },
    ],
  },
  {
    id: "merchant.rollout.phases",
    page: "merchant",
    label: "Rollout · phases + perks",
    anchor: "/merchant#rollout",
    fields: [
      { kind: "text", id: "merchant.rollout.phase.alpha.label", label: "Alpha · label", default: "Alpha" },
      { kind: "text", id: "merchant.rollout.phase.alpha.status", label: "Alpha · status", default: "Complete" },
      { kind: "text", id: "merchant.rollout.phase.alpha.desc", label: "Alpha · description", default: "We tested flows, edge cases, and reliability with an internal team.", multiline: true },
      { kind: "text", id: "merchant.rollout.phase.beta.label", label: "Beta · label", default: "Beta" },
      { kind: "text", id: "merchant.rollout.phase.beta.status", label: "Beta · status", default: "Now — invite only" },
      { kind: "text", id: "merchant.rollout.phase.beta.desc", label: "Beta · description", default: "Select merchants + partners in focused Dubai corridors.", multiline: true },
      { kind: "text", id: "merchant.rollout.phase.live.label", label: "Live · label", default: "Live" },
      { kind: "text", id: "merchant.rollout.phase.live.status", label: "Live · status", default: "Coming soon" },
      { kind: "text", id: "merchant.rollout.phase.live.desc", label: "Live · description", default: "Public availability with expanded corridors and lower fees.", multiline: true },
      { kind: "text", id: "merchant.rollout.perks.eyebrow", label: "Perks · eyebrow", default: "Early merchant perks" },
      { kind: "text", id: "merchant.rollout.perks.title.line1", label: "Perks · title line 1", default: "Join early," },
      { kind: "text", id: "merchant.rollout.perks.title.line2", label: "Perks · title line 2", default: "earn more." },
      { kind: "text", id: "merchant.rollout.benefit.item1", label: "Benefit 1", default: "Priority visibility in matching" },
      { kind: "text", id: "merchant.rollout.benefit.item2", label: "Benefit 2", default: "Direct access to the team" },
      { kind: "text", id: "merchant.rollout.benefit.item3", label: "Benefit 3", default: "Early liquidity incentives" },
      { kind: "text", id: "merchant.rollout.benefit.item4", label: "Benefit 4", default: "Lower fees during pilot" },
    ],
  },
  {
    id: "merchant.requirements.items",
    page: "merchant",
    label: "Requirements · cards",
    anchor: "/merchant#requirements",
    fields: [
      { kind: "text", id: "merchant.requirements.item1.title", label: "Req 1 · title", default: "Liquidity ready" },
      { kind: "text", id: "merchant.requirements.item1.text", label: "Req 1 · text", default: "You can provide liquidity for at least one corridor.", multiline: true },
      { kind: "text", id: "merchant.requirements.item2.title", label: "Req 2 · title", default: "Fast execution" },
      { kind: "text", id: "merchant.requirements.item2.text", label: "Req 2 · text", default: "You respond quickly and complete trades reliably.", multiline: true },
      { kind: "text", id: "merchant.requirements.item3.title", label: "Req 3 · title", default: "Basic verification" },
      { kind: "text", id: "merchant.requirements.item3.text", label: "Req 3 · text", default: "Phone, email, and wallet — no full KYC during Beta.", multiline: true },
      { kind: "text", id: "merchant.requirements.item4.title", label: "Req 4 · title", default: "Policy compliant" },
      { kind: "text", id: "merchant.requirements.item4.text", label: "Req 4 · text", default: "You follow trade rules and dispute policy.", multiline: true },
    ],
  },
  {
    id: "merchant.howitworks",
    page: "merchant",
    label: "How it works · steps",
    anchor: "/merchant#howitworks",
    fields: [
      { kind: "text", id: "merchant.howitworks.eyebrow", label: "Eyebrow", default: "Three taps. One settled trade." },
      { kind: "text", id: "merchant.howitworks.title", label: "Title", default: "How merchants execute on Blip" },
      { kind: "text", id: "merchant.howitworks.step1.title", label: "Step 1 · title", default: "Find a new order" },
      { kind: "text", id: "merchant.howitworks.step1.subtitle", label: "Step 1 · subtitle", default: "Live order feed." },
      { kind: "text", id: "merchant.howitworks.step1.desc", label: "Step 1 · description", default: "Incoming user requests stream into your dashboard the moment they're created — filtered by your corridors, limits, and risk profile.", multiline: true },
      { kind: "text", id: "merchant.howitworks.step2.title", label: "Step 2 · title", default: "Accept before others" },
      { kind: "text", id: "merchant.howitworks.step2.subtitle", label: "Step 2 · subtitle", default: "First merchant wins." },
      { kind: "text", id: "merchant.howitworks.step2.desc", label: "Step 2 · description", default: "150+ merchants compete on every order. The fastest competitive bid wins — one tap to lock it in.", multiline: true },
      { kind: "text", id: "merchant.howitworks.step3.title", label: "Step 3 · title", default: "Execute & settle" },
      { kind: "text", id: "merchant.howitworks.step3.subtitle", label: "Step 3 · subtitle", default: "Escrow handles the rest." },
      { kind: "text", id: "merchant.howitworks.step3.desc", label: "Step 3 · description", default: "Funds release the moment fiat lands. On-chain proof, deterministic settlement, no chargebacks.", multiline: true },
    ],
  },
  {
    id: "merchant.faq",
    page: "merchant",
    label: "FAQ · merchant",
    anchor: "/merchant#faq",
    fields: [
      { kind: "text", id: "merchant.faq.title", label: "Title", default: "Frequently Asked Questions" },
      { kind: "text", id: "merchant.faq.sub", label: "Subtitle", default: "Everything you need to know about how Blip works, onboarding,  and trading flow.", multiline: true },
      { kind: "text", id: "merchant.faq.item1.question", label: "Q1", default: "How do I receive orders?" },
      { kind: "text", id: "merchant.faq.item1.answer", label: "A1", default: "Orders appear in your dashboard feed. You accept to lock.", multiline: true },
      { kind: "text", id: "merchant.faq.item2.question", label: "Q2", default: "Can I adjust pricing to win orders?" },
      { kind: "text", id: "merchant.faq.item2.answer", label: "A2", default: "Yes, within allowed ranges.", multiline: true },
      { kind: "text", id: "merchant.faq.item3.question", label: "Q3", default: "What if a user doesn't complete?" },
      { kind: "text", id: "merchant.faq.item3.answer", label: "A3", default: "The trade follows the escrow timeline and dispute rules.", multiline: true },
      { kind: "text", id: "merchant.faq.item4.question", label: "Q4", default: "Do I need full KYC?" },
      { kind: "text", id: "merchant.faq.item4.answer", label: "A4", default: "Not during early Beta. Basic verification is required.", multiline: true },
      { kind: "text", id: "merchant.faq.item5.question", label: "Q5", default: "Which corridors launch first?" },
      { kind: "text", id: "merchant.faq.item5.answer", label: "A5", default: "Starting with Dubai-focused corridors, expanding in stages.", multiline: true },
    ],
  },

  // ─── HOME ARRAYS (agent: home) ───
  {
    id: "home.bankless.cards",
    page: "home",
    label: "Bankless · 3 feature cards",
    anchor: "/#bankless",
    fields: [
      { kind: "text", id: "home.bankless.item1.tag", label: "Card 1 · tag", default: "Pricing" },
      { kind: "text", id: "home.bankless.item1.title", label: "Card 1 · title", default: "Best rates, guaranteed." },
      { kind: "text", id: "home.bankless.item1.caption", label: "Card 1 · caption", default: "Competitive liquidity providers compress spreads on every transfer.", multiline: true },
      { kind: "text", id: "home.bankless.item2.tag", label: "Card 2 · tag", default: "Speed" },
      { kind: "text", id: "home.bankless.item2.title", label: "Card 2 · title", default: "Send money in minutes." },
      { kind: "text", id: "home.bankless.item2.caption", label: "Card 2 · caption", default: "Cross-border transfers without banking delays.", multiline: true },
      { kind: "text", id: "home.bankless.item3.tag", label: "Card 3 · tag", default: "Security" },
      { kind: "text", id: "home.bankless.item3.title", label: "Card 3 · title", default: "Secure by design." },
      { kind: "text", id: "home.bankless.item3.caption", label: "Card 3 · caption", default: "Escrow, reputation, and on-chain verification built into every transaction.", multiline: true },
    ],
  },
  {
    id: "home.trust.cards",
    page: "home",
    label: "Trust · 4 architecture cards",
    anchor: "/#trust",
    fields: [
      { kind: "text", id: "home.trust.item1.tag", label: "Card 1 · tag", default: "Settlement" },
      { kind: "text", id: "home.trust.item1.title", label: "Card 1 · title", default: "Deterministic settlement" },
      { kind: "text", id: "home.trust.item1.desc", label: "Card 1 · desc", default: "No ambiguity. No manual intervention. Every outcome predefined by protocol rules.", multiline: true },
      { kind: "text", id: "home.trust.item2.tag", label: "Card 2 · tag", default: "Guarantees" },
      { kind: "text", id: "home.trust.item2.title", label: "Card 2 · title", default: "Escrow + execution guarantees" },
      { kind: "text", id: "home.trust.item2.desc", label: "Card 2 · desc", default: "Funds locked before execution. Enforced by smart contracts, not promises.", multiline: true },
      { kind: "text", id: "home.trust.item3.tag", label: "Card 3 · tag", default: "Verification" },
      { kind: "text", id: "home.trust.item3.title", label: "Card 3 · title", default: "On-chain verification" },
      { kind: "text", id: "home.trust.item3.desc", label: "Card 3 · desc", default: "Every transaction verifiable on-chain. Full transparency, zero trust required.", multiline: true },
      { kind: "text", id: "home.trust.item4.tag", label: "Card 4 · tag", default: "Resilience" },
      { kind: "text", id: "home.trust.item4.title", label: "Card 4 · title", default: "System isolation" },
      { kind: "text", id: "home.trust.item4.desc", label: "Card 4 · desc", default: "No single point of failure. Each component operates independently.", multiline: true },
    ],
  },
  {
    id: "home.liquidity.stats",
    page: "home",
    label: "Liquidity · 4 stat tiles",
    anchor: "/#liquidity",
    fields: [
      { kind: "text", id: "home.liquidity.stat1.label", label: "Stat 1 · label", default: "Speed" },
      { kind: "text", id: "home.liquidity.stat1.old", label: "Stat 1 · old", default: "3–5 days" },
      { kind: "text", id: "home.liquidity.stat1.new", label: "Stat 1 · new", default: "< 60s" },
      { kind: "text", id: "home.liquidity.stat2.label", label: "Stat 2 · label", default: "Fees" },
      { kind: "text", id: "home.liquidity.stat2.old", label: "Stat 2 · old", default: "5–7%" },
      { kind: "text", id: "home.liquidity.stat2.new", label: "Stat 2 · new", default: "< 1%" },
      { kind: "text", id: "home.liquidity.stat3.label", label: "Stat 3 · label", default: "Transparency" },
      { kind: "text", id: "home.liquidity.stat3.old", label: "Stat 3 · old", default: "Zero" },
      { kind: "text", id: "home.liquidity.stat3.new", label: "Stat 3 · new", default: "Full" },
      { kind: "text", id: "home.liquidity.stat4.label", label: "Stat 4 · label", default: "Availability" },
      { kind: "text", id: "home.liquidity.stat4.old", label: "Stat 4 · old", default: "9–5" },
      { kind: "text", id: "home.liquidity.stat4.new", label: "Stat 4 · new", default: "24/7" },
    ],
  },
  {
    id: "home.howitworks.stages",
    page: "home",
    label: "How it works · 6 stage copy",
    anchor: "/#howitworks",
    fields: [
      { kind: "text", id: "home.howitworks.stage.sendUsdt.headline", label: "Send USDT · headline", default: "Send USDT." },
      { kind: "text", id: "home.howitworks.stage.sendUsdt.subline", label: "Send USDT · subline", default: "From your wallet to the world.", multiline: true },
      { kind: "text", id: "home.howitworks.stage.instantMatch.headline", label: "Instant Match · headline", default: "Instant Match." },
      { kind: "text", id: "home.howitworks.stage.instantMatch.subline", label: "Instant Match · subline", default: "Fastest matching engine pairs you with a merchant.", multiline: true },
      { kind: "text", id: "home.howitworks.stage.lockEscrow.headline", label: "Lock & Escrow · headline", default: "Lock & Escrow." },
      { kind: "text", id: "home.howitworks.stage.lockEscrow.subline", label: "Lock & Escrow · subline", default: "Funds locked in smart contract escrow.", multiline: true },
      { kind: "text", id: "home.howitworks.stage.fiatPayout.headline", label: "Fiat Payout · headline", default: "Fiat Payout." },
      { kind: "text", id: "home.howitworks.stage.fiatPayout.subline", label: "Fiat Payout · subline", default: "Recipient receives cash or bank transfer in local currency.", multiline: true },
      { kind: "text", id: "home.howitworks.stage.proofOnChain.headline", label: "Proof on Chain · headline", default: "Proof on Chain." },
      { kind: "text", id: "home.howitworks.stage.proofOnChain.subline", label: "Proof on Chain · subline", default: "Every settlement verified and recorded on-chain.", multiline: true },
      { kind: "text", id: "home.howitworks.stage.globalRemittance.headline", label: "Global Remittance · headline", default: "Global Remittance." },
      { kind: "text", id: "home.howitworks.stage.globalRemittance.subline", label: "Global Remittance · subline", default: "Send money to anyone, anywhere across the globe.", multiline: true },
    ],
  },
  {
    id: "home.appshowcase.cards",
    page: "home",
    label: "App showcase · 7 mobile cards",
    anchor: "/#appshowcase",
    fields: [
      { kind: "text", id: "home.appshowcase.item1.title", label: "Card 1 · title", default: "Best rates, guaranteed" },
      { kind: "text", id: "home.appshowcase.item1.desc", label: "Card 1 · desc", default: "Seamless multi-corridor transfers.", multiline: true },
      { kind: "text", id: "home.appshowcase.item2.title", label: "Card 2 · title", default: "Instant matching" },
      { kind: "text", id: "home.appshowcase.item2.desc", label: "Card 2 · desc", default: "Fastest engine pairs you with merchants.", multiline: true },
      { kind: "text", id: "home.appshowcase.item3.title", label: "Card 3 · title", default: "Settled on-chain" },
      { kind: "text", id: "home.appshowcase.item3.desc", label: "Card 3 · desc", default: "Every transfer verified on Solana.", multiline: true },
      { kind: "text", id: "home.appshowcase.item4.title", label: "Card 4 · title", default: "Merchant Dashboard" },
      { kind: "text", id: "home.appshowcase.item4.desc", label: "Card 4 · desc", default: "Live P&L · Active orders · Blipscan.", multiline: true },
      { kind: "text", id: "home.appshowcase.item5.title", label: "Card 5 · title", default: "Escrow secured" },
      { kind: "text", id: "home.appshowcase.item5.desc", label: "Card 5 · desc", default: "Funds locked in smart-contract escrow.", multiline: true },
      { kind: "text", id: "home.appshowcase.item6.title", label: "Card 6 · title", default: "Non-custodial wallet" },
      { kind: "text", id: "home.appshowcase.item6.desc", label: "Card 6 · desc", default: "Your keys, your funds. Always.", multiline: true },
      { kind: "text", id: "home.appshowcase.item7.title", label: "Card 7 · title", default: "Global reach" },
      { kind: "text", id: "home.appshowcase.item7.desc", label: "Card 7 · desc", default: "150+ countries · Any currency.", multiline: true },
    ],
  },
];
